### ISSUE TITLE
Crystal 1.0.0 compatibility

### ISSUE THREAD

**Issue by vjousse** [MakeNowJust/noir#34]
By default `noir` isn't compatible with crystal 1.0.0 projects as it doesn't specify a crystal version in its `shards.yml`

Specifying `crystal: 1.0.0` in its `shards.yml` makes it compatible out of the box with crystal 1.0.0.
What about freezing the current version with a release tag and releasing a new version compatible with 1.0.0 projects?

**Comment by makenowjust** [comment]
Close by #35
