### ISSUE TITLE
`find_lexer` doesn't work

### ISSUE THREAD

**Issue by mishushakov** [MakeNowJust/noir#41]
Crystal 1.2.0 (2021-10-13)

LLVM: 11.1.0
Default target: x86_64-apple-macosx

my code

```crystal
require "noir"
puts Noir.find_lexer("css")
```

output

```

```

**Comment by makenowjust** [comment]
You should add `require "noir/lexers/css"` before `find_lexer`. By default, any lexers are not registered.

**Comment by mishushakov** [comment]
ok, that worked, thanks!
